add some test cases for audit events
code0-tech/sagittarius pull request #146
Opened 2024-04-19 23:50 UTC by Knerio

2024-04-24 17:45 UTC, Taucher2003 requested changes

2024-04-24 17:45 UTC, Taucher2003 commented on spec/services/users/login_service_spec.rb
> +        details: { other_key: current_user.send(other_key), method: 'username_and_password' }
This does make a difference. With `other_key:` you expect the audit event to have a `other_key` key in the details, while `other_key =>` expects a key with the value of `other_key` in the details.
```suggestion
        details: { other_key => current_user.send(other_key), method: 'username_and_password' }
```

2024-04-24 17:45 UTC, Taucher2003 commented on spec/services/users/login_service_spec.rb
> +    def check_audit_events(user, key, other_key)
Thinking again, this should probably be a `shared_example` instead of a method

2024-04-28 19:33 UTC, Knerio commented on spec/services/users/login_service_spec.rb
> +    def check_audit_events(user, key, other_key)
This should be resolved via [b16c38f](https://github.com/code0-tech/sagittarius/pull/146/commits/b16c38f78ea6891caa70913ac164cbd46dc298c3)

2024-05-01 18:51 UTC, Taucher2003 approved these changes

2024-05-01 18:51 UTC, merged