Create organization projects and create mutation
code0-tech/sagittarius pull request #174
Opened 2024-05-12 08:56 UTC by Knerio

It works, but somehow the mutation test fails

contributes https://github.com/code0-tech/sagittarius/issues/173

2024-05-12 20:01 UTC, Taucher2003 requested changes

2024-05-12 20:01 UTC, Taucher2003 commented on spec/services/organization_projects/create_service_spec.rb
> +    it { expect { service_response }.not_to create_audit_event(:organization_created) }
```suggestion
    it { expect { service_response }.not_to create_audit_event(:organization_project_created) }
```

2024-05-12 20:13 UTC, Knerio commented on spec/requests/graphql/mutation/organization_projects/create_mutation_spec.rb
> +    context 'when organization project name is taken in another organization' do
Fixed with [6a1a2d6](https://github.com/code0-tech/sagittarius/pull/174/commits/6a1a2d61b2cfc3dca0f85c5bfc70ca598af2c22a)

2024-05-12 20:14 UTC, Knerio commented on app/models/organization_project.rb
> +  # end
Fiex

2024-05-14 17:36 UTC, Taucher2003 approved these changes

2024-05-14 17:36 UTC, merged