201 implement totp mfa
code0-tech/sagittarius pull request #249
Opened 2024-07-25 20:56 UTC by Knerio

2024-07-29 20:18 UTC, Taucher2003 requested changes

2024-07-29 20:18 UTC, Taucher2003 commented on app/services/users/mfa/totp/validate_secret_service.rb
> +          unless Ability.allowed?(@current_user, :manage_mfa, @current_user)
```suggestion
          unless Ability.allowed?(current_user, :manage_mfa, current_user)
```

2024-07-29 20:18 UTC, Taucher2003 commented on app/services/users/mfa/totp/validate_secret_service.rb
> +              return ServiceResponse.error(message: 'Error while saving user', payload: @current_user.errors)
```suggestion
            current_user.totp_secret = totp_secret
            unless current_user.save
              return ServiceResponse.error(message: 'Error while saving user', payload: current_user.errors)
```

2024-07-29 20:18 UTC, Taucher2003 commented on app/services/users/mfa/totp/validate_secret_service.rb
> +              target: @current_user
```suggestion
              author_id: current_user.id,
              entity: current_user,
              details: { type: :totp },
              target: current_user
```

2024-07-29 20:18 UTC, Taucher2003 commented on app/services/users/mfa/totp/validate_secret_service.rb
> +            ServiceResponse.success(message: 'TOTP secret validated', payload: @current_user)
```suggestion
            ServiceResponse.success(message: 'TOTP secret validated', payload: current_user)
```

2024-07-29 20:18 UTC, Taucher2003 commented on db/migrate/20240718183207_add_totp_field_to_user_for_mfa.rb
> +    add_column :users, :totp_secret, :text, unique: { allow_nil_duplicate: true }
The model already has this validation, so the db should include it as well. You need to re-run this migration, so that `structure.sql` gets updated.
```suggestion
    add_column :users, :totp_secret, :text, unique: { allow_nil_duplicate: true }, limit: 32
```

2024-07-29 20:18 UTC, Taucher2003 commented on db/migrate/20240726141600_create_backup_codes.rb
> +    create_table :backup_codes do |t|
I'm thinking if we should rename it to `:user_mfa_backup_codes`. But maybe `:backup_codes` is enough.

I currently can't think of a thing where we would need the `BackupCode` name for something else in the future.

2024-07-29 20:18 UTC, Taucher2003 commented on db/migrate/20240726141600_create_backup_codes.rb
> +      t.text :token, limit: 10
```suggestion
      t.text :token, limit: 10, null: false
```

2024-07-29 20:18 UTC, Taucher2003 commented on db/migrate/20240726141600_create_backup_codes.rb
> +      t.references :user, null: false, foreign_key: true
If it does not cascade, we wouldn't be able to delete users with backup codes anymore.

Also, this column does not need it's index because it is covered in the index that we create manually below.
```suggestion
      t.references :user, null: false, foreign_key: { on_delete: :cascade }, index: false
```

2024-07-29 20:18 UTC, Taucher2003 commented on docs/content/graphql/mutation/userslogin.md
> +| `mfa` | [`MfaInput`](../input_object/mfainput.md) | The data of the mfa login |
Seems like this file is missing. Either you forgot it in the commit or I need to check if I missed it in the generation task.

2024-07-31 16:41 UTC, Knerio commented on docs/content/graphql/mutation/userslogin.md
> +| `mfa` | [`MfaInput`](../input_object/mfainput.md) | The data of the mfa login |
The generation task isnt working properly

2024-08-04 13:51 UTC, Taucher2003 approved these changes
Tested locally as well and worked as expected.

The unconfigured secret_key_base is not yet a problem because we don't have a released version or any deployed version of this app, so I can handle this as a follow up instead of blocking the merge here. 🚀

2024-08-04 13:52 UTC, merged